ASP.NET_MVC/ASP.NET_MVC/Controllers/VentaController.cs
using ASP.NET_MVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ASP.NET_MVC.Controllers
{
    public class VentaController : Controller
    {
        private FarmaVETEntities db = new FarmaVETEntities();

        public ActionResult Index()
        {
            /*
            var orderView = new OrderView();
            orderView.medicamentoOrder = new List<MedicamentoOrder>();
            Session["orderView"] = orderView;
            */
            List<Boleta> data = db.Boleta.Take(5).OrderByDescending(x => x.BoletaId).ToList();
            return View(data);
        }

        //
        // GET: /Venta/
        public ActionResult NewOrder()
        {
            var orderView = new OrderView();
            orderView = Session["orderView"] as OrderView;
            return View(orderView);
        }

        [HttpPost]
        public ActionResult NewOrder(OrderView orderView, string Cliente)
        {
            using (var transaction = db.Database.BeginTransaction())
            {
                try
                {
                    orderView = Session["orderView"] as OrderView;
                    orderView.Cliente = Cliente;
                    if (Cliente.Equals(""))
                    {
                        ViewBag.MessageError = "Ingrese un cliente";
                        return View(orderView);
                    }
                    if (orderView.medicamentoOrder.Count == 0)
                    {
                        ViewBag.MessageError = "Agregue detalle";
                        return View(orderView);
                    }
                    var order = new Boleta
                    {
                        Cliente = orderView.Cliente,
                        FechaVenta = DateTime.Now,
                        MontoTotal = orderView.MontoTotal,
                        CantidadItems = orderView.medicamentoOrder.Count,
                    };
                    db.Boleta.Add(order);
                    db.SaveChanges();

                    foreach (var item in orderView.medicamentoOrder)
                    {
                        var detalle = new DetalleBoleta
                        {
                            BoletaId = order.BoletaId,
                            Cantidad = item.Cantidad,
                            MedicamentoId = item.MedicamentoId,
                            Precio = item.Precio,
                            SubTotal = item.SubTotal
                        };
                        db.DetalleBoleta.Add(detalle);
                        int stock = db.Medicamento.Find(item.MedicamentoId).Stock;
                        if(stock >= item.Cantidad){
                            db.SP_ReducirStockMedicamento(item.MedicamentoId, item.Cantidad);
                        }
                        else if(stock == 0)
                        {
                            orderView.medicamentoOrder.Remove(item);
                            transaction.Rollback();
                            ViewBag.MessageError = "Medicamento"+ string.Format(" {0} {1} {2} removido, porque ya no tiene existencias",
                                item.Nombre, item.DescripcionEspecie, item.DescripcionTipo);
                            return View("NewOrder", orderView);
                        }
                        else
                        {
                            transaction.Rollback();
                            ViewBag.MessageError = "Medicamento" + string.Format(" {0} {1} {2} tiene {3} y se quiere comprar {4}",
                                item.Nombre, item.DescripcionEspecie, item.DescripcionTipo, stock, item.Cantidad);
                            return View("NewOrder", orderView);
                        }
                        db.SaveChanges();
                    }

                    transaction.Commit();

                    ViewBag.MessageSuccess = string.Format("La orden: {0}, fue registrada", order.BoletaId);

                    orderView = new OrderView();
                    orderView.medicamentoOrder = new List<MedicamentoOrder>();
                    Session["orderView"] = orderView;

                    return View("NewOrder", orderView);
                }
                catch(NullReferenceException)
                {
                    orderView = new OrderView();
                    orderView.medicamentoOrder = new List<MedicamentoOrder>();
                    Session["orderView"] = orderView;
                    transaction.Rollback();
                    ViewBag.MessageError = "Debe agregar detalle";
                    return View(orderView);
                }
                catch (Exception e)
                {
                    transaction.Rollback();
                    ViewBag.MessageError = e.Message;
                    return View(orderView);
                }
            }
        }

        public ActionResult AddMedicamento()
        {
            ViewBag.Medicamentos = new SelectList(db.Medicamento, "MedicamentoId", "MedicamentoEspecie");
            return View();
        }

        [HttpPost]
        public ActionResult AddMedicamento(MedicamentoOrder m, int Cantidad)
        {
            ViewBag.Medicamentos = new SelectList(db.Medicamento, "MedicamentoId", "MedicamentoEspecie");
            var MedicamentoId = int.Parse(Request["MedicamentoId"]);
            var orderView = Session["orderView"] as OrderView;

            try
            {
                var medicamento = db.Medicamento.Find(MedicamentoId);
                if (MedicamentoId < 1)
                {
                    ViewBag.MessageError = "Seleccione un producto";
                    return View(m);
                }
                if (medicamento == null)
                {
                    ViewBag.MessageError = "Producto no existe";
                    return View(m);
                }
                if (Cantidad <= 0)
                {
                    ViewBag.MessageError = "Ingrese una cantidad mayor a 0";
                    return View(m);
                }
                if (medicamento.Stock < Cantidad)
                {
                    ViewBag.MessageError = "Medicamento no tiene stock suficiente";
                    return View(m);
                }
                if (medicamento.Stock == 0)
                {
                    ViewBag.MessageError = "Medicamento no tiene existencias";
                    return View(m);
                }

                m = orderView.medicamentoOrder.Find(x => x.MedicamentoId == MedicamentoId);

                if (m == null)
                {
                    m = new MedicamentoOrder
                    {
                        Nombre = medicamento.Nombre,
                        DescripcionEspecie = medicamento.Especie.Descripcion,
                        DescripcionTipo = medicamento.TipoMedicamento.Descripcion,
                        MedicamentoId = medicamento.MedicamentoId,
                        SubTotal = medicamento.Precio * Cantidad,
                        Precio = medicamento.Precio,
                        Cantidad = Cantidad
                    };
                    orderView.medicamentoOrder.Add(m);
                    orderView.MontoTotal += m.SubTotal;
                }
                else
                {
                    m.Cantidad += Cantidad;
                    m.SubTotal += medicamento.Precio * Cantidad;
                    orderView.MontoTotal += medicamento.Precio * Cantidad;
                }

                ViewBag.MessageSuccess = "Se agrego producto";
                return View("NewOrder", orderView);
            }
            catch (NullReferenceException)
            {
                orderView = new OrderView();
                orderView.medicamentoOrder = new List<MedicamentoOrder>();
                Session["orderView"] = orderView;
                ViewBag.MessageError = "Ya puede agregar detalle";
                return View(m);
            }
            catch (Exception e)
            {
                ViewBag.MessageError = e.Message;
                return View(m);
            }
        }

        public ActionResult EditMedicamento(int? id)
        {
            var orderView = Session["orderView"] as OrderView;
            var data = orderView.medicamentoOrder.Find(x => x.MedicamentoId == id);
            return View(data);
        }

        [HttpPost]
        public ActionResult EditMedicamento(MedicamentoOrder m, int Cantidad)
        {
            var MedicamentoId = int.Parse(Request["MedicamentoId"]);

            var orderView = Session["orderView"] as OrderView;

            var medicamento = db.Medicamento.Find(MedicamentoId);

            m = orderView.medicamentoOrder.Find(x => x.MedicamentoId == medicamento.MedicamentoId);

            if (MedicamentoId < 1)
            {
                ViewBag.MessageError = "Seleccione un producto";
                return View(m);
            }
            if (medicamento == null)
            {
                ViewBag.MessageError = "Producto no existe";
                return View(m);
            }
            if (Cantidad <= 0)
            {
                ViewBag.MessageError = "Ingrese una cantidad mayor a 0";
                return View(m);
            }
            if (medicamento.Stock < Cantidad)
            {
                ViewBag.MessageError = "Medicamento no tiene stock suficiente";
                return View(m);
            }
            if (medicamento.Stock == 0)
            {
                ViewBag.MessageError = "Medicamento no tiene existencias";
                return View(m);
            }

            orderView.MontoTotal -= medicamento.Precio * m.Cantidad;
            m.Cantidad = Cantidad;
            m.SubTotal = medicamento.Precio * Cantidad;
            orderView.MontoTotal += medicamento.Precio * Cantidad;

            ViewBag.MessageSuccess = "Se edito producto";

ASP.NET_MVC/ASP.NET_MVC/Views/Venta/AddMedicamento.cshtml
@model ASP.NET_MVC.Models.MedicamentoOrder
@{
    ViewBag.Title = "Agregar al Detalle";
}

<h2>Agregar al Detalle</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @if (ViewBag.MessageSuccess != null)
        {
            <div class="message-form">
                <div class="alert alert-success">
                    <h4>@ViewBag.MessageSuccess</h4>
                </div>
            </div>
        }
        @if (ViewBag.MessageError != null)
        {
            <div class="message-form">
                <div class="alert alert-danger">
                    <h4>@ViewBag.MessageError</h4>
                </div>
            </div>
        }

        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, "MedicamentoId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MedicamentoId", (IEnumerable<SelectListItem>)ViewBag.Medicamentos, "Seleccione Medicamento", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MedicamentoId)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cantidad, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cantidad)
                @Html.ValidationMessageFor(model => model.Cantidad)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Agregar" class="btn btn-success" />
                <a href="~/venta/neworder" class="btn btn-info">Regresar</a>
            </div>
        </div>
    </div>
}

ASP.NET_MVC/ASP.NET_MVC/Views/Venta/DeleteMedicamento.cshtml
@model ASP.NET_MVC.Models.MedicamentoOrder
@{
    ViewBag.Title = "Eliminar del Detalle";
}

<h2>Eliminar del Detalle</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @if (ViewBag.MessageSuccess != null)
        {
            <div class="message-form">
                <div class="alert alert-success">
                    <h4>@ViewBag.MessageSuccess</h4>
                </div>
            </div>
        }
        @if (ViewBag.MessageError != null)
        {
            <div class="message-form">
                <div class="alert alert-danger">
                    <h4>@ViewBag.MessageError</h4>
                </div>
            </div>
        }

        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.HiddenFor(model => model.MedicamentoId)
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control", @disabled = "" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DescripcionEspecie, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.DescripcionEspecie, new { @class = "form-control", @disabled = "" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DescripcionTipo, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.DescripcionTipo, new { @class = "form-control", @disabled = "" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cantidad, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Cantidad, new { @class = "form-control", @disabled = "" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Eliminar" class="btn btn-danger" />
                <a href="~/venta/neworder" class="btn btn-info">Regresar</a>
            </div>
        </div>
    </div>
}

ASP.NET_MVC/ASP.NET_MVC/Views/Venta/EditMedicamento.cshtml
@model ASP.NET_MVC.Models.MedicamentoOrder
@{
    ViewBag.Title = "Editar al Detalle";
}

<h2>Editar Detalle</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @if (ViewBag.MessageSuccess != null)
        {
            <div class="message-form">
                <div class="alert alert-success">
                    <h4>@ViewBag.MessageSuccess</h4>
                </div>
            </div>
        }
        @if (ViewBag.MessageError != null)
        {
            <div class="message-form">
                <div class="alert alert-danger">
                    <h4>@ViewBag.MessageError</h4>
                </div>
            </div>
        }

        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.HiddenFor(model => model.MedicamentoId)
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control", @disabled = "" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DescripcionEspecie, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.DescripcionEspecie, new { @class = "form-control", @disabled = "" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DescripcionTipo, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.DescripcionTipo, new { @class = "form-control", @disabled = "" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cantidad, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cantidad)
                @Html.ValidationMessageFor(model => model.Cantidad)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Editar" class="btn btn-success" />
                <a href="~/venta/neworder" class="btn btn-info">Regresar</a>
            </div>
        </div>
    </div>
}

ASP.NET_MVC/ASP.NET_MVC/Views/Venta/Index.cshtml
@model List<ASP.NET_MVC.Models.Boleta>

@{
    ViewBag.Title = "Listado de Ventas";
}

<div class="breadcrumb">
    <div class="row">
        <div class="col-sm-10">
            <h2>Listado de Ventas</h2>
        </div>
        <div class="col-sm-2 text-right">
            <a href="~/venta/neworder" class="btn btn-success">Registrar Venta</a>
        </div>
    </div>
</div>

<table id="orden" class="table table-bordered">
    <thead>
        <tr>
            <th></th>
            <th>Boleta Nº</th>
            <th>Cliente</th>
            <th>Fecha de Venta</th>
            <th>Total Items</th>
            <th>Monto Total</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td class="text-center"><i class="fa fa-chevron-right" id="@item.BoletaId"></i></td>
                <td class="boletaId">@item.BoletaId</td>
                <td>@item.Cliente</td>
                <td>@item.FechaVenta</td>
                <td>@item.CantidadItems</td>
                <td>@item.MontoTotal</td>
            </tr>
            <tr id="fila-@item.BoletaId" style="display:none"><td></td><td colspan="5">@Html.Action("_DetalleVenta", new { id = item.BoletaId})</td></tr>
        }
    </tbody>

</table>

ASP.NET_MVC/ASP.NET_MVC/Views/Venta/ListadoVentas.cshtml
@model List<ASP.NET_MVC.Models.Boleta>

@{
    ViewBag.Title = "Listado de Ventas";
}

<h2>Listado de Ventas</h2>

<table class="table table-bordered">
    <thead>
        <tr>
            <th></th>
            <th>Boleta Nº</th>
            <th>Cliente</th>
            <th>Fecha de Venta</th>
            <th>Total Items</th>
            <th>Monto Total</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td class="text-center"><i class="fa fa-chevron-right"></i></td>
                <td>@item.BoletaId</td>
                <td>@item.Cliente</td>
                <td>@item.FechaVenta</td>
                <td>@item.CantidadItems</td>
                <td>@item.MontoTotal</td>
            </tr>
            <tr><td>@item.MontoTotal</td><td colspan="5">@Html.Action("_DetalleVenta", new { id = item.BoletaId})</td></tr>
        }
    </tbody>

</table>

ASP.NET_MVC/ASP.NET_MVC/Views/Venta/NewOrder.cshtml
@model ASP.NET_MVC.Models.OrderView
@{
    ViewBag.Title = "Registrar Venta";
}

<h2>Registrar Venta</h2>

@using (Html.BeginForm("NewOrder", "Venta", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @if (ViewBag.MessageSuccess != null)
        {
            <div class="message-form">
                <div class="alert alert-success">
                    <h4>@ViewBag.MessageSuccess</h4>
                </div>
            </div>
        }
        @if (ViewBag.MessageError != null)
        {
            <div class="message-form">
                <div class="alert alert-danger">
                    <h4>@ViewBag.MessageError</h4>
                </div>
            </div>
        }

        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Cliente, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Cliente, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Cliente)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10 col-md-offset-2">
                <input type="submit" value="Registrar Venta" class="btn btn-success" />
                <a href="~/venta/addmedicamento" class="btn btn-primary">Seleccionar Medicamento</a>
            </div>
        </div>
    </div>
}

@if(Model != null){
    
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Medicamento.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Medicamento.DescripcionTipo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Medicamento.DescripcionEspecie)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Medicamento.Precio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Medicamento.Cantidad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Medicamento.SubTotal)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    @for (var i = 0; i < Model.medicamentoOrder.Count; i++)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => Model.medicamentoOrder[i].Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => Model.medicamentoOrder[i].DescripcionTipo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => Model.medicamentoOrder[i].DescripcionEspecie)
            </td>
            <td>
                @Html.DisplayFor(modelItem => Model.medicamentoOrder[i].Precio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => Model.medicamentoOrder[i].Cantidad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => Model.medicamentoOrder[i].SubTotal)
            </td>
            <td>
                <a href="~/venta/EditMedicamento/@Model.medicamentoOrder[i].MedicamentoId" class="btn btn-success fa fa-pencil" title="Editar"></a>
                <a href="~/venta/DeleteMedicamento/@Model.medicamentoOrder[i].MedicamentoId" class="btn btn-danger fa fa-trash" title="Eliminar"></a>
            </td>
        </tr>
    }
    </tbody>
    <tfoot>
        <tr><td class="bold">Monto Total</td><td colspan="5" class="text-right">@Html.DisplayFor(modelItem => Model.MontoTotal)</td><td></td></tr>
    </tfoot>
</table>   
}

ASP.NET_MVC/ASP.NET_MVC/Views/Venta/_DetalleVenta.cshtml
@model List<ASP.NET_MVC.Models.DetalleBoleta>

@{
    ViewBag.Title = "Listado de Ventas";
}
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Medicamento</th>
            <th>Especie</th>
            <th>Tipo de Medicamento</th>
            <th>Precio</th>
            <th>Cantidad</th>
            <th>Sub Total</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Medicamento.Nombre</td>
                <td>@item.Medicamento.Especie.Descripcion</td>
                <td>@item.Medicamento.TipoMedicamento.Descripcion</td>
                <td>@item.Precio</td>
                <td>@item.Cantidad</td>
                <td>@item.SubTotal</td>
            </tr>
        }
    </tbody>

</table>